SET TIME ZONE 'UTC';

ALTER TABLE features_5m
    ADD COLUMN IF NOT EXISTS return_1h DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS volume_accel DOUBLE PRECISION NOT NULL DEFAULT 0;
