SET TIME ZONE 'UTC';

ALTER TABLE features_5m
    ADD COLUMN IF NOT EXISTS volume_velocity_rank_pct DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS buy_sell_ratio_rank_pct DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS trade_intensity_rank_pct DOUBLE PRECISION NOT NULL DEFAULT 0;
