SET TIME ZONE 'UTC';

ALTER TABLE features_5m
    ADD COLUMN IF NOT EXISTS relative_momentum DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS volume_shock DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS macd_proxy DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS rsi_14 DOUBLE PRECISION NOT NULL DEFAULT 50;
